{{- if and .Values.server.enabled .Values.server.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "server.serviceAccountName" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
  {{- with .Values.server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if and .Values.webclient.enabled .Values.webclient.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webclient.serviceAccountName" . }}
  labels:
    {{- include "webclient.labels" . | nindent 4 }}
  {{- with .Values.webclient.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if and .Values.adminClient.enabled .Values.adminClient.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "adminClient.serviceAccountName" . }}
  labels:
    {{- include "adminClient.labels" . | nindent 4 }}
  {{- with .Values.adminClient.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if and .Values.database.enabled .Values.database.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "database.serviceAccountName" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
  {{- with .Values.database.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if and .Values.backup.enabled .Values.backup.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backup.serviceAccountName" . }}
  labels:
    {{- include "backup.labels" . | nindent 4 }}
  {{- with .Values.backup.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}